### ISSUE TITLE
فارسی نویسی در مخازن جامعه ری‌اکت ایران

### ISSUE THREAD

**Issue by amerllica** [iran-react-community/todo-list#2]
<div dir="rtl">
با سلام خدمت دوست عزیز که این ریپو رو ایجاد کردید و دارید زحمت می‌کشید و کاملش می‌کنید.
<br />
رویهء اصلی‌ای که با دوستان پیاده سازی کردیم و تصمیم گرفتیم که ادامه بدیم این بود که جامعه‌ء فارسی‌ای بسازیم و آموزش‌ها همگی فارسی باشند. خیلی خیلی بهتر خواهش در صورتی که فایل readme رو فارسی بنویسید تا افرادی که زبان انگلیسی روبه خوبی فرا نگرفتند بتونند از این کار ارزشمند شما استفاده کنند.
</div>

**Comment by ali-master** [comment]
<p style="direction: rtl; text-align: right;">
سلام وقتتون بخیر

در اول راه ممنونم از توجهتون.
باهاتون موافقم و پیشنهاد خوبیه اما٬
واقعیتش به دلیل اینکه این محیط گیت هاب خب یک محیط بین المملی هستش و ایجاب میکنه بخاطر دیده شدن در سطح بین المملی فارسی ننویسیم اما میتونیم یک فایل README فارسی هم در کنار نسخه انگلیسی هر پروژه ایجاد کنیم و منتشر کنیم و فکر میکنم این مورد بتونه به همه کمک کنه در بهتر دیده شدن پروژه ها
</p>
